### ISSUE TITLE
Error when running sample

### ISSUE THREAD

**Issue by kevinkleine** [bcarruthers/garnet#18]
Hi there,

F# noob here, trying to run a sample on Manjaro Linux. I have .NET 6 installed. When executing "dotnet run" in the sample folder Garnet.Samples.Flocking, I'm getting the following error. Am I doing something wrong?

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Garnet.Graphics.Environment.addPathVariables() in /home/kevin/p/k/fsharp/garnet/samples/Garnet.Toolkit/Window.fs:line 38
   at Garnet.Graphics.WindowRenderer..ctor(WindowSettings settings)
   at Garnet.Composition.Systems.AddGraphicsDevice(Container c) in /home/kevin/p/k/fsharp/garnet/samples/Garnet.Toolkit/Systems.fs:line 52
   at Garnet.Composition.Systems.AddGraphics(Container c) in /home/kevin/p/k/fsharp/garnet/samples/Garnet.Toolkit/Systems.fs:line 210
   at Garnet.Composition.Systems.AddDefaultSystems(Container c) in /home/kevin/p/k/fsharp/garnet/samples/Garnet.Toolkit/Systems.fs:line 220
   at Garnet.Samples.Flocking.StartupSystem.add(Container c) in /home/kevin/p/k/fsharp/garnet/samples/Garnet.Samples.Flocking/Startup.fs:line 31
   at Program.s@8.Invoke(Container c)
   at <StartupCode$Garnet>.$Containers.Pipe #1 stage #1 at line 235@235.Invoke(FSharpFunc`2 sys) in /home/kevin/p/k/fsharp/garnet/src/Garnet/Containers.fs:line 235
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@99.DoMoveNext(b& curr) in /build/dotnet-core/src/sources/src/fsharp/artifacts/source-build/self/src/src/FSharp.Core/seq.fs:line 102
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in /build/dotnet-core/src/sources/src/fsharp/artifacts/source-build/self/src/src/FSharp.Core/seq.fs:line 84
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source) in /build/dotnet-core/src/sources/src/fsharp/artifacts/source-build/self/src/src/FSharp.Core/seq.fs:line 984
   at Garnet.Composition.Disposable.Create(IEnumerable`1 items) in /home/kevin/p/k/fsharp/garnet/src/Garnet/Messaging.fs:line 335
   at Garnet.Composition.Container.AddSystems(IEnumerable`1 systems) in /home/kevin/p/k/fsharp/garnet/src/Garnet/Containers.fs:line 236
   at Program.main(String[] _arg1) in /home/kevin/p/k/fsharp/garnet/samples/Garnet.Samples.Flocking/Program.fs:line 7
   ```

**Comment by bcarruthers** [comment]
I haven't tried it on any Linux distributions, so there might be work needed to support graphics and other platform code in the samples. I'd expect Garnet library to work if called from a simple console app though.
